version: "3.9"

services:
  database:
    image: postgres
    container_name: database_challenge
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=challenge
      - POSTGRES_DB=challenge
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: challenge
    ports: 
      - 3333:3333
    volumes: 
      - .:/usr/app
    links: 
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local